version: '3'

services:
    mysql:
        image: mysql:5
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: development
        ports:
            - '3306:3306'
