### test

POST http://localhost:3002/cats HTTP/1.1
content-type: application/json

{
    "name": "rin",
    "age": 10,
    "breed": "雑種"
}

### post 2

POST http://localhost:3002/api/vi/cats HTTP/1.1
content-type: application/json

{
    "name": "hani",
    "age": "5",
    "breed": "茶トラ"
}

### GET cats
GET http://localhost:3002/cats HTTP/1.1
content-type: application/json

### GET cats
GET http://localhost:3002/cats/a HTTP/1.1
content-type: application/json

### GET
GET http://localhost:3002/ HTTP/1.1
content-type: application/json

### post user追加

POST http://localhost:3002/users HTTP/1.1
content-type: application/json

{
    "name": "いもうと",
    "age": 10,
    "email": "imouto@gmail.com"
}

### post user追加

POST http://localhost:3002/hanii-api/v1/photos/create HTTP/1.1
content-type: application/json

{
    "name": "りん",
    "description": "猫の写真",
    "filename": "rin.jpg",
    "views": 1,
    "isPublished": true
}

### user 追加
POST http://localhost:3002/hanii-api/v1/users/create HTTP/1.1
content-type: application/json

{
    "name": "あああ",
    "email": "test1@gmail.com",
    "password": "password",
    "gender": "男",
    "photos": [
        {
            "name": "りん",
            "description": "猫の写真",
            "filename": "rin.jpg",
            "views": 1,
            "isPublished": true
        }
    ]
}
