### test

POST http://localhost:3002/cats HTTP/1.1
content-type: application/json

{
    "name": "rin",
    "age": 10,
    "breed": "雑種"
}

### post 2

POST http://localhost:3002/cats HTTP/1.1
content-type: application/json

{
    "name": "hani",
    "age": 5,
    "breed": "茶トラ"
}

### GET cats
GET http://localhost:3002/cats HTTP/1.1
content-type: application/json
