export const SEQUELIZE = 'SEQUELIZE'
export const USER_REPOSITORY = 'USER_REPOSITORY'
export const ENV_DEVELOPMENT = 'development'
export const ENV_TEST = 'test'
export const ENV_PRODUCTION = 'production'
